Make wallpaper shuffler more flexible

diff --git a/tag-arch/bin/shuffle_wallpapers b/tag-arch/bin/shuffle_wallpapers
--- a/tag-arch/bin/shuffle_wallpapers
+++ b/tag-arch/bin/shuffle_wallpapers
@@ -2,7 +2,19 @@
 
 set -ex
 
-for jpg in $(find "/home/max/Pictures/wallpapers" -name "*.jpg" | sort --random-sort); do
+dropbox_location="/home/max/Dropbox/Pictures/wallpapers"
+local_location="/home/max/Pictures/wallpapers"
+
+if [ -d "$dropbox_location" ]; then
+  dir="$dropbox_location"
+elif [ -d "$local_location" ]; then
+  dir="$local_location"
+else
+  echo "Can't find wallpapers"
+  exit 1
+fi
+
+for jpg in $(find "$dir" -name "*.jpg" | sort --random-sort); do
   feh --no-xinerama --bg-fill "$jpg"
   sleep 240
 done
